const videoMetadata = [
["fishing dreamcast.mov","fishing pole","fish"],
["guitar hero regular.mov","guitar","music"],
["contra bongos.mov","drum","fight"],
["mario bowling ball.mov","bowling ball","run"],
["mario steering wheel.mov","steering wheel","run"],
["tetris steering wheel.mov","steering wheel","puzzle"],
["car videogame with real car as controller.mov","steering wheel","drive"],
["real car with ps2 controller.mov","default","drive"],
["call of duty with steering wheel.mov","steering wheel","fight"],
["dark souls steering wheel.mov","steering wheel","fight"],
["fishing pole dark souls.mov","fishing pole","fight"],
["call of duty rock band .mov","drum","fight"],
["thrasher skate and destroy ps1.mov","default","skate"],
["metro cross NES skateboard.mov","default","skate"],
["skitching sega genesis 1994.mov","default","skate"],
["tony hawk ride actual skateboard.mov","skateboard","skate"],
["cuphead ddr.mov","dance pad","fight"],
["resident evil dance pad.mov","dance pad","fight"],
["tekken on dance pad.mov","dance pad","fight"],
["james bond golden eye dance pad.mov","dance pad","fight"],
["super mario ddr pad.mov","dance pad","run"],
["smash bros ddr pad.mov","dance pad","fight"],
["street fighter with ddr pad.mov","dance pad","fight"],
["guitar hero modern warfare.mov","guitar","fight"],
["pro evolution soccer ps1.mov","default","soccer"],
["final soccer vr.mov","default","soccer"],
["fifa soccer 17 xbox one.mov","default","soccer"],
["wii fit u soccer.mov","balance pad","soccer"],
["n64 internaitonal superstar soccer.mov","default","soccer"],
["virtua stiker 2 dreamcast .mov","default","soccer"],
["kick off amiga 1989.mov","default","soccer"],
["pele's soccer atari 2600 1981.mov","default","soccer"],
["super formation soccer 1992.mov","default","soccer"],
["Atari Soccer (1980).mov","default","soccer"],
["Donkey Konga.mov","drum","music"],
["dk bongo for switch.mov","drum","fight"],
["NES super glove ball.mov","glove","tennis"],
["NES power glove controls drone.mov","glove","fly"],
["pong.mov","default","tennis"],
["wii bowling ball perfect for Boxing.mov","bowling ball","fight"],
["soul caliber with fishing controller.mov","fishing pole","fight"],
["sega activator.mov","activator","fight"],
["playchoice 10 tennis.mov","default","tennis"],
["ambush alley.mov","light gun","fight"],
["ddr.mov","dance pad","dance"],
["Virtual Boy Tennis.mov","default","tennis"],
["bigbuckhunter.mov","light gun","hunt"],
["htcvive tennis.mov","default","tennis"],
["wiitennis.mov","default","tennis"],
["tennisfortwo.mov","default","tennis"]
];
